=== mickelus/tetra/schemas/stats/stat_bar.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://tetra.mickelus.se/schemas/1.20/stats/stat_bar.schema.json",
    "title": "Stat Bar",
    "description": "Defines how a statbar displays, including labels, formatting, tooltip and possibly bar indicators.",
    "type": "object",
    "properties": {
        "type": {
            "type": "string",
            "$comment": "There's only one type registered in vanilla tetra, but this can be set if some other mod has registered other statbar types."
        },
        "key": {
            "$ref": "../resource_location.schema.json",
            "$comment": "The localization key for the stat bar, the localized value will be displayed next to the numerical label above the stat bar. Probably something along the lines of 'mymod.stats.attack_damage'."
        },
        "stat": {
            "$ref": "stat_getter/ref.schema.json",
            "$comment": "The stat to display in the stat bar, this value backs how the bar is displayed and the label."
        },
        "min": {
            "type": "number",
            "description": "The minimum value for the stat bar, sets the lower bound for the actual bar."
        },
        "max": {
            "type": "number",
            "description": "The maximum value for the stat bar, sets the upper bound for the actual bar."
        },
        "label": {
            "$ref": "label_getter/ref.schema.json",
            "$comment": "Defines how the actual value of the stat is displayed above the bar."
        },
        "tooltip": {
            "$ref": "tooltip_getter/ref.schema.json",
            "$comment": "Defines the tooltip for the stat bar, this is displayed when hovering over the stat bar."
        },
        "indicators": {
            "type": "array",
            "items": {
                "$ref": "../resource_location.schema.json"
            },
            "$comment": "An array of resource locations referencing directories (relative stat_indicators/) of indicators which should be displayed for this stat bar."
        },
        "contexts": {
            "type": "array",
            "description": "Defines which UIs to show this stat bar in.",
            "items": {
                "type": "string",
                "examples": [ "tetra:workbench", "tetra:holosphere" ]
            }
        },
        "generateSorter": {
            "description": "If set to true, registers a stat sorter with the same label, stat and format as this stat bar.",
            "type": "boolean"
        }
    },
    "required": [ "key", "min", "max", "contexts", "stat", "label", "tooltip" ],
    "examples": [
        {
            "type": "tetra:default",
            "key": "tetra.stats.attack_damage",
            "contexts": [ "tetra:workbench" ],
            "min": 0,
            "max": 40,
            "stat": {
                "type": "tetra:sum",
                "stats": [
                    {
                        "type": "tetra:attribute",
                        "attribute": "generic.attack_damage"
                    },
                    {
                        "type": "tetra:sum",
                        "stats": [
                            {
                                "type": "tetra:multiply",
                                "stats": [
                                    {
                                        "type": "tetra:enchantment",
                                        "enchantment": "minecraft:sharpness"
                                    }
                                ],
                                "factor": 0.5
                            }
                        ],
                        "offset": 0.5
                    }
                ]
            },
            "label": {
                "type": "tetra:basic",
                "format": "double_decimal",
                "diff_format": "double_decimal"
            },
            "tooltip": {
                "type": "tetra:default",
                "key": "tetra.stats.attack_damage.tooltip",
                "stats": [
                    {
                        "type": "tetra:sum",
                        "stats": [
                            {
                                "type": "tetra:attribute",
                                "attribute": "generic.attack_damage"
                            },
                            {
                                "type": "tetra:sum",
                                "stats": [
                                    {
                                        "type": "tetra:multiply",
                                        "stats": [
                                            {
                                                "type": "tetra:enchantment",
                                                "enchantment": "minecraft:sharpness"
                                            }
                                        ],
                                        "factor": 0.5
                                    }
                                ],
                                "offset": 0.5
                            }
                        ],
                        "attribute": "generic.attack_damage"
                    }
                ],
                "formatters": [
                    {
                        "type": "tetra:basic",
                        "format": "double_decimal"
                    }
                ]
            },
            "indicators": [ "tetra:attack_damage/shared", "tetra:attack_damage/normalized" ]
        }
    ]
}

=== mickelus/tetra/src/main/resources/assets/tetra/stat_bars/attack_damage_normalized.json
{
    "type": "tetra:default",
    "key": "dam",
    "contexts": [ "tetra:holosphere" ],
    "min": 0,
    "max": 20,
    "stat": {
        "type": "tetra:attribute",
        "attribute": "generic.attack_damage",
        "ignoreBase": true
    },
    "label": {
        "type": "tetra:basic",
        "format": "double_decimal",
        "diff_format": "double_decimal"
    },
    "tooltip": {
        "type": "tetra:default",
        "key": "tetra.stats.attack_damage_normalized.tooltip",
        "stats": [
            {
                "type": "tetra:sum",
                "stats": [
                    {
                        "type": "tetra:attribute",
                        "attribute": "generic.attack_damage",
                        "ignoreBase": true
                    },
                    {
                        "type": "tetra:sum",
                        "stats": [
                            {
                                "type": "tetra:multiply",
                                "stats": [
                                    {
                                        "type": "tetra:enchantment",
                                        "enchantment": "minecraft:sharpness"
                                    }
                                ],
                                "factor": 0.5
                            }
                        ],
                        "offset": 0.5
                    }
                ],
                "attribute": "generic.attack_damage"
            }
        ],
        "formatters": [
            {
                "type": "tetra:basic",
                "format": "double_decimal"
            }
        ]
    },
    "indicators": [
        {
            "key": "tetra.stats.sharpness",
            "texture": "tetra:textures/gui/glyphs.png",
            "textureX": 136,
            "textureY": 160,
            "stat": {
                "type": "tetra:sum",
                "stats": [
                    {
                        "type": "tetra:multiply",
                        "stats": [
                            {
                                "type": "tetra:enchantment",
                                "enchantment": "minecraft:sharpness"
                            }
                        ],
                        "factor": 0.5
                    }
                ],
                "offset": 0.5
            },
            "tooltip": {
                "type": "tetra:default",
                "key": "tetra.stats.sharpness.tooltip",
                "stats": [
                    {
                        "type": "tetra:sum",
                        "stats": [
                            {
                                "type": "tetra:multiply",
                                "stats": [
                                    {
                                        "type": "tetra:enchantment",
                                        "enchantment": "minecraft:sharpness"
                                    }
                                ],
                                "factor": 0.5
                            }
                        ],
                        "offset": 0.5
                    }
                ],
                "formatters": [
                    {
                        "type": "tetra:basic",
                        "format": "single_decimal"
                    }
                ]
            }
        }
    ]
}

=== mickelus/tetra/src/main/resources/assets/tetra/stat_bars/vexing.json
{
    "type": "tetra:default",
    "key": "tetra.stats.vexing",
    "contexts": [ "tetra:workbench" ],
    "min": 0,
    "max": 100,
    "stat": {
        "type": "tetra:multiply",
        "stats": [
            {
                "type": "tetra:effect_level",
                "effect": "vexing"
            }
        ],
        "factor": 10
    },
    "label": {
        "type": "tetra:basic",
        "format": "percentage",
        "diff_format": "percentage"
    },
    "tooltip": {
        "type": "tetra:default",
        "key": "tetra.stats.vexing.tooltip",
        "stats": [
            {
                "type": "tetra:effect_efficiency",
                "effect": "vexing"
            },
            {
                "type": "tetra:multiply",
                "stats": [
                    {
                        "type": "tetra:effect_level",
                        "effect": "vexing"
                    }
                ],
                "factor": 10
            }
        ],
        "formatters": [
            {
                "type": "tetra:basic",
                "format": "percentage"
            },
            {
                "type": "tetra:basic",
                "format": "percentage"
            }
        ]
    },
    "generateSorter": true
}

=== mickelus/tetra/src/main/resources/assets/tetra/stat_bars/heroic.json
{
    "type": "tetra:default",
    "key": "tetra.stats.heroic",
    "contexts": [
        "tetra:workbench"
    ],
    "min": 0,
    "max": 100,
    "stat": {
        "type": "tetra:effect_level",
        "effect": "heroic"
    },
    "label": {
        "type": "tetra:basic",
        "format": "percentage",
        "diff_format": "percentage"
    },
    "tooltip": {
        "type": "tetra:default",
        "key": "tetra.stats.heroic.tooltip",
        "stats": [
            {
                "type": "tetra:effect_level",
                "effect": "heroic"
            },
            {
                "type": "tetra:effect_efficiency",
                "effect": "heroic"
            }
        ]
    }
}

=== mickelus/tetra/src/main/resources/assets/tetra/stat_bars/attack_damage.json
{
    "type": "tetra:default",
    "key": "tetra.stats.attack_damage",
    "contexts": [ "tetra:workbench" ],
    "min": 0,
    "max": 40,
    "stat": {
        "type": "tetra:sum",
        "stats": [
            {
                "type": "tetra:attribute",
                "attribute": "generic.attack_damage"
            },
            {
                "type": "tetra:sum",
                "stats": [
                    {
                        "type": "tetra:multiply",
                        "stats": [
                            {
                                "type": "tetra:enchantment",
                                "enchantment": "minecraft:sharpness"
                            }
                        ],
                        "factor": 0.5
                    }
                ],
                "offset": 0.5
            }
        ]
    },
    "label": {
        "type": "tetra:basic",
        "format": "double_decimal",
        "diff_format": "double_decimal"
    },
    "tooltip": {
        "type": "tetra:standard",
        "key": "tetra.stats.attack_damage.tooltip",
        "stats": [
            {
                "type": "tetra:sum",
                "stats": [
                    {
                        "type": "tetra:attribute",
                        "attribute": "generic.attack_damage"
                    },
                    {
                        "type": "tetra:sum",
                        "stats": [
                            {
                                "type": "tetra:multiply",
                                "stats": [
                                    {
                                        "type": "tetra:enchantment",
                                        "enchantment": "minecraft:sharpness"
                                    }
                                ],
                                "factor": 0.5
                            }
                        ],
                        "offset": 0.5
                    }
                ],
                "attribute": "generic.attack_damage"
            }
        ],
        "formatters": [
            {
                "type": "tetra:basic",
                "format": "double_decimal"
            }
        ]
    },
    "indicators": [ "tetra:attack_damage/shared/", "tetra:attack_damage/standard/" ]
}
