=== mickelus/tetra/schemas/schematics/schematic.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://tetra.mickelus.se/schemas/1.20/schematics.schema.json",
    "title": "Schematic",
    "description": "Data defining a schematic. Schematics determine how modules are crafted, and how existing major modules can be improved.",
    "type": "object",
    "properties": {
        "replace": {
            "type": "boolean",
            "description": "Marks if this should replace or merge with existing entries (if any) for this schematic definition. The default behaviour for upgrade schematics added by other mods and datapacks is to merge values set by those into the existing entry (if any). By setting replace to true it's possible to completely replace schematics registered by tetra, which can be useful when one wants to remove something."
        },
        "localizationKey": {
            "type": "string",
            "description": "The key used for localized human readable strings such as name and description. If this is not available the key field is used for picking up localized strings instead, which is preferable in most cases. This field is useful when multiple schematics should use the same name, description etc."
        },
        "slots": {
            "type": "array",
            "description": "An array of slots which this schematic is applicable for.",
            "items": {
                "type": "string"
            }
        },
        "keySuffixes": {
            "type": "array",
            "description": "Suffixes, used when crafted modules should have different keys depending on slot (e.g. pickaxe head keys end with \"_left\" or \"_right\" so that different textures can be used depending on the slot. Optional, but if provided it has to have the same length as the slots field.",
            "items": {
                "type": "string"
            }
        },
        "materialSlotCount": {
            "type": "number",
            "description": "The number of material that can be used when crafting with this schematic, currently only a value 0 or 1 is supported."
        },
        "repair": {
            "type": "boolean",
            "description": "States if a repair schematic should also be generated based on this schematic. Useful when the crafted module is repaired using the same materials and tools as if it was crafted."
        },
        "hone": {
            "type": "boolean",
            "description": "Defines if this schematic should only be applicable when the player has a honing attempt available for the item."
        },
        "requirement": {
            "$ref": "crafting_requirements/ref.schema.json",
            "$comment": "If present, this schematic will only be visible and applicable when the game state matches this requirement."
        },
        "materialRevealSlot": {
            "type": "number",
            "description": "If set this schematic will only be visible if the player carries at least one itemstack that will produce an outcome if placed in the slot at the provided index."
        },
        "displayType": {
            "type": "string",
            "description": "Defines the outline around the schematic glyph, visible in most views where players interact with the schematic somehow. \"minor\" and \"major\" display a similar outline as minor and major modules, \"improvement\" looks like a major module outline with a plus, \"other\" has no outline and the outline can instead be part of the glyph.",
            "enum": [
                "other",
                "improvement",
                "minor",
                "major"
            ]
        },
        "rarity": {
            "type": "string",
            "description": "The rarity of a schematic affects how it is rendered. Colors and effects are used to differentiate between effects.",
            "enum": [
                "temporary",
                "hone",
                "basic"
            ]
        },
        "glyph": {
            "description": "The glyph displayed for this schematic, preferably the same as the module it will be used to craft but with no tint.",
            "type": "object",
            "properties": {
                "textureX": {
                    "type": "number",
                    "description": "Horizontal offset (from the left) for the glyph in the sprite sheet"
                },
                "textureY": {
                    "type": "number",
                    "description": "Vertical offset (from the top) for the glyph in the sprite sheet"
                },
                "textureLocation": {
                    "type": "string",
                    "description": "The resource location for the texture where the glyph is located."
                }
            }
        },
        "translation": {
            "type": "object",
            "description": "Used to display some information about how material properties translate into stats for the module or improvement that the schematic crafts.",
            "properties": {
            }
        },
        "applicableMaterials": {
            "type": "array",
            "description": "Used to display hints about which materials that can be used for this schematic, strings starting with # are considered as materials, others as item IDs.",
            "items": {
                "type": "string"
            }
        },
        "outcomes": {
            "type": "array",
            "description": "An array of all potential outcomes of this schematic.",
            "items": {
                "$ref": "outcome_ref.schema.json"
            }
        }
    },
    "examples": [
        {
            "slots": [ "double/head_left", "double/head_right" ],
            "keySuffixes": [ "_left", "_right" ],
            "materialSlotCount": 1,
            "glyph": {
                "textureX": 64,
                "textureY": 0
            },
            "displayType": "major",
            "outcomes": [
                {
                    "material": {
                        "tag": "forge:obsidian"
                    },
                    "requiredTools": {
                        "hammer": 6
                    },
                    "moduleKey": "double/basic_hammer",
                    "moduleVariant": "basic_hammer/obsidian",
                    "improvements": {
                        "arrested": 0
                    }
                },
                {
                    "materials": [ "tetra:metal/" ],
                    "countFactor": 2,
                    "toolOffset": 1,
                    "moduleKey": "double/basic_hammer",
                    "moduleVariant": "basic_hammer/"
                }
            ]
        }
    ]
}

=== mickelus/tetra/src/main/resources/data/tetra/schematics/shield/plate/heater.json
{
    "replace": true,
    "slots": [
        "shield/plate"
    ],
    "materialSlotCount": 1,
    "displayType": "major",
    "glyph": {
        "textureX": 32,
        "textureY": 48
    },
    "translation": {
        "primaryAttributes": {
            "tetra:ability_damage": 4
        },
        "secondaryAttributes": {
            "tetra:ability_damage": 1,
            "tetra:ability_cooldown": -2
        },
        "primaryEffects": {
            "blocking": 2
        },
        "secondaryEffects": {
            "blocking": -1
        },
        "tertiaryEffects": {
            "blocking": 2
        },
        "durability": 4,
        "integrity": -3,
        "magicCapacity": 3
    },
    "outcomes": [
        {
            "materials": ["tetra:wood/", "tetra:metal/", "tetra:bone/", "tetra:misc/vent_plate"],
            "moduleKey": "shield/heater",
            "moduleVariant": "heater/"
        }
    ]
}

=== mickelus/tetra/src/main/resources/data/tetra/schemas/toolbelt/belt/belt_1.json
{
    "replace": true,
    "slots": [
        "toolbelt/belt"
    ],
    "materialSlotCount": 1,
    "requirement": {
        "type": "tetra:modular_item",
        "variants": {
            "belt/sash": "toolbelt/belt"
        }
    },
    "glyph": {
        "textureY": 16
    },
    "displayType": "minor",
    "outcomes": [
        {
            "material": {
                "item": "minecraft:leather"
            },
            "requiredCapabilities": {
                "cut": 2
            },
            "moduleKey": "toolbelt/belt",
            "moduleVariant": "belt/leather"
        }
    ]
}

=== mickelus/tetra/src/main/resources/data/tetra/schematics/toolbelt/belt/belt_1.json
{
    "replace": true,
    "slots": [
        "toolbelt/belt"
    ],
    "materialSlotCount": 1,
    "requirement": {
        "type": "tetra:modular_item",
        "modules": [["toolbelt/belt_wool"]]
    },
    "glyph": {
        "textureY": 16
    },
    "displayType": "minor",
    "outcomes": [
        {
            "material": {
                "item": "minecraft:leather"
            },
            "requiredTools": {
                "cut": 2
            },
            "moduleKey": "toolbelt/belt",
            "moduleVariant": "belt/leather"
        }
    ]
}

=== mickelus/tetra/src/main/resources/data/tetra/schematics/single/socket.json
{
    "replace": true,
    "slots": [
        "single/binding"
    ],
    "materialSlotCount": 1,
    "displayType": "minor",
    "glyph": {
        "textureX": 80,
        "textureY": 16
    },
    "outcomes": [
        {
            "materials": ["tetra:socket/"],
            "moduleKey": "single/socket",
            "moduleVariant": "single_socket/"
        }
    ]
}

=== mickelus/tetra/src/main/resources/data/tetra/schematics/sword/short_blade.json
{
    "replace": true,
    "slots": [
        "sword/blade"
    ],
    "materialSlotCount": 1,
    "displayType": "major",
    "glyph": {
        "textureX": 32
    },
    "translation": {
        "primaryAttributes": {
            "generic.attack_damage": 3
        },
        "secondaryAttributes": {
            "generic.attack_speed": -1
        },
        "secondaryEffects": {
            "jab": -1
        },
        "tools": {
            "cut": [2, 3]
        },
        "durability": 4,
        "integrity": -3,
        "magicCapacity": 3
    },
    "outcomes": [
        {
            "materials": ["tetra:wood/", "tetra:stone/", "tetra:metal/", "tetra:gem/", "tetra:bone/"],
            "moduleKey": "sword/short_blade",
            "moduleVariant": "short_blade/"
        }
    ]
}

=== mickelus/tetra/src/main/resources/data/tetra/schematics/double/perk_socket_0.json
{
    "replace": true,
    "slots": [ "double/binding" ],
    "materialSlotCount": 1,
    "displayType": "minor",
    "rarity": "temporary",
    "requirement": {
        "type": "tetra:perk",
        "perk": "support",
        "level": {
            "min": 1
        }
    },
    "glyph": {
        "textureX": 160,
        "textureY": 16
    },
    "outcomes": [
        {
            "materials": [ "tetra:socket/" ],
            "moduleKey": "double/perk_socket_0",
            "moduleVariant": "double_perk_socket_0/",
            "experienceFactor": 1
        }
    ]
}

=== mickelus/tetra/src/main/resources/data/tetra/schematics/single/handle/long_handle.json
{
    "replace": true,
    "slots": [
        "single/handle"
    ],
    "materialSlotCount": 1,
    "displayType": "major",
    "glyph": {
        "textureX": 112,
        "textureY": 32
    },
    "translation": {
        "primaryAttributes": {
            "forge:reach_distance": 1
        },
        "secondaryAttributes": {
            "generic.attack_speed": -2
        },
        "tertiaryAttributes": {
            "forge:reach_distance": 2
        },
        "durability": 1,
        "integrity": 3,
        "magicCapacity": 3
    },
    "outcomes": [
        {
            "materials": [
                "tetra:wood/", "tetra:metal/",
                "tetra:bone/", "tetra:misc/blaze_rod", "tetra:misc/end_rod", "tetra:misc/forged_beam", "tetra:misc/stick"
            ],
            "moduleKey": "single/long_handle",
            "moduleVariant": "long_handle/"
        }
    ]}

=== mickelus/tetra/src/main/resources/data/tetra/schematics/double/extractor/hone_extractor_4.json
{
    "replace": true,
    "slots": ["double/head_right"],
    "materialSlotCount": 0,
    "hone": true,
    "rarity": "hone",
    "displayType": "major",
    "glyph": {
        "textureX": 144,
        "textureY": 48
    },
    "requirement": {
        "type": "tetra:modular_item",
        "modules": [["double/extractor_right"]],
        "improvements": {
            "extractor_hone/potency": 3
        }
    },
    "outcomes": [
        {
            "requiredTools": {
                "hammer": 7
            },
            "improvements": {
                "extractor_hone/potency": 4
            }
        }
    ]
}
